export const initialNotes = [
  {
    id: 1,
    name: "Health",
    date: new Date('2023-07-31'),
    category: "Task",
    content: "I'm gonna have a dentist appointment on the 3/5/2023, I moved it from 5/5/2023",
    archived: false,
  },
  {
    id: 2,
    name: "Shopping",
    date: new Date('2023-07-31'),
    category: 'Task',
    content: 'Remember to buy groceries tomorrow',
    archived: true,
  },
  {
    id: 3,
    name: "Rest",
    date: new Date('2023-07-30'),
    category: 'Random Thought',
    content: 'Had a great time at the beach today',
    archived: false,
  },
  {
    id: 4,
    name: "New Feature",
    date: new Date('2023-07-29'),
    category: 'Idea',
    content: 'Working on a new project idea',
    archived: false,
  },
  {
    id: 5,
    name: "Study",
    date: new Date('2023-07-28'),
    category: 'Task',
    content: 'Need to prepare for the upcoming presentation',
    archived: false,
  },
  {
    id: 6,
    name: "Health",
    date: new Date('2023-07-28'),
    category: 'Task',
    content: 'I have a doctor appointment on 2/8/2023',
    archived: false,
  },
  {
    id: 7,
    name: "New Feature",
    date: new Date('2023-07-27'),
    category: 'Idea',
    content: 'Thinking about redecorating the living room',
    archived: false,
  },
];
